### ISSUE TITLE
Download from vscode ext page to install, doesnt work

### ISSUE THREAD

**Issue by jkone27** [mhutch/MonoDevelop.MSBuildEditor#106]
When i download it opens the vsix without opening it in vscode

<img width="234" alt="image" src="https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/10419217/bb9f0233-139b-42b9-b24d-e007e9b0243a">

**Comment by mhutch** [comment]
Sorry, the extension currently only supports Visual Studio. Support for Visual Studio Code is planned but will be a fair bit of work.

https://github.com/mhutch/MonoDevelop.MSBuildEditor/issues/107
