### ISSUE TITLE
String format placeholder being displayed, unsubstituted

### ISSUE THREAD

**Issue by drewnoakes** [mhutch/MonoDevelop.MSBuildEditor#108]
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/350947/d33055a5-95e0-4325-abc3-8b9eb7d5a748)

https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/357a6dac03f8720fd9842a1dc119afc862ba0da8/MonoDevelop.MSBuild/Language/CoreDiagnostics.cs#L629

Looking on GitHub I can't see exactly where the `string.Format` call happens (or is supposed to happen) for this string. Hopefully it's not too tricky to find and fix this though.

**Comment by KirillOsenkov** [comment]
here perhaps?

https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/357a6dac03f8720fd9842a1dc119afc862ba0da8/MonoDevelop.MSBuild/Language/MSBuildDocumentValidator.cs#L523

**Comment by drewnoakes** [comment]
Indeed. It seems that args is unused in AddFixableError.
