### ISSUE TITLE
Tolerate <> in MSBuildRootDocument.Parse

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.MSBuildEditor#122]
For document `<>` seeing this NullReferenceException:

<HTML>
<BODY>
<TABLE><TR><TD>&nbsp;</TD><TD>MonoDevelop.MSBuild</TD><TD>MSBuildRootDocument.Parse Line 182</TD></TR></TABLE>

</BODY>
</HTML>

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/679326/38aa7c09-73c5-4128-9cb6-fc06db9162d3)

previous.Frameworks is null

**Comment by KirillOsenkov** [comment]
For the same document, also seeing another exception in background parser via GetHighlightsAsync:

<HTML>
<BODY>
<TABLE><TR><TD>&nbsp;</TD><TD>System</TD><TD>Stack`1.Peek Line 216</TD></TR><TR><TD>&nbsp;</TD><TD>MonoDevelop.Xml.Core</TD><TD>XmlTagState.PushChar Line 66</TD></TR><TR><TD>&nbsp;</TD><TD>MonoDevelop.Xml.Core</TD><TD>XmlParser.Push Line 92</TD></TR><TR><TD>&nbsp;</TD><TD>MonoDevelop.Xml.Editor</TD><TD>XmlBackgroundParser.GetSpineParser Line 100</TD></TR><TR><TD>&nbsp;</TD><TD>MonoDevelop.Xml.Editor</TD><TD>XmlHighlightEndTagTagger.GetHighlightsAsync Line 39</TD></TR><TR><TD>&nbsp;</TD><TD>MonoDevelop.Xml.Editor</TD><TD>HighlightTagger`2.TimerFired Line 77</TD></TR></TABLE>

</BODY>
</HTML>

**Comment by mhutch** [comment]
Attempting to repro the first issue in some new tests in #126 but I can't seem to make it happen

**Comment by KirillOsenkov** [comment]
The scenario is basically turn on first-chance exceptions in the debugger and type up a simple project from scratch. Now I’m realizing it might have been ‘<P>’ or ‘<P’ because I’m not exactly sure what was the exact contents of the buffer at the time this happened.

**Comment by mhutch** [comment]
Have you seen any of these recently? I haven't, so I'm of a mind to close this.

**Comment by KirillOsenkov** [comment]
Seems fine on latest
