### ISSUE TITLE
PublishRepositoryUrl needs to be a boolean

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.MSBuildEditor#127]
Currently `PublishRepositoryUrl` is treated as a URL, but it's really a boolean:

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/679326/0fb2a73f-193d-42c6-95e0-30bdcb22a86c)

See here for usage:
https://github.com/NuGet/NuGet.Client/blob/82955234207a57a9eadcbf6d41addefd5a994f35/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L292-L293

**Comment by simplexidev** [comment]
I was just coming to post this issue. Can confirm.
