### ISSUE TITLE
Highlight unbalanced parentheses

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.MSBuildEditor#133]
I think we could do a very good job showing a diagnostic here:
https://github.com/dotnet/msbuild/issues/6421

**Comment by mhutch** [comment]
FWIW we do detect this, we just don't show a precise position

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/183285/72e290f3-e044-4ffa-b592-d6c38ac8159f)

**Comment by KirillOsenkov** [comment]
Good enough for me! I think there was another case where it didn't show an error but I forgot what it was, next time I'll include a repro.
