### ISSUE TITLE
Task completion inside targets

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.MSBuildEditor#150]
Should maybe offer all available tasks inside targets:

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/679326/2e735b0d-daa5-4451-8df0-29ac05573b06)

at the very least, maybe some common ones, Message, Exec, Copy, Delete, RemoveDuplicates, etc.

**Comment by mhutch** [comment]
Oops, broke this by accidentally removing the `isAbstract` from the `Task` element :/

**Comment by mhutch** [comment]
I special cased the `Message` task's `Importance` attribute as well so it gets validation and completion, turns out it's strongly typed internally but stringly typed on the task property.
