### ISSUE TITLE
NuGet versions do not support globs and ranges

### ISSUE THREAD

**Issue by Vasilich** [mhutch/MonoDevelop.MSBuildEditor#166]
if use release-dependent versions in form  
```xml
<PackageReference Include="xxx" Version="[16.3.*,17.0)" />
```
that is valid and works as expected, the popup says that "The value "[16.3.*,17.0)" not a valid suffixed version format"
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/1168434/526f6201-cae1-4688-a838-ea3008462729)
But it shows that not for all lines having same format :/

**Comment by OronDF343** [comment]
This error even appears on simpler versions using just an `*`:
```xml
    <PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="8.0.*" />
```
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/5132940/b24de59f-5a07-48e6-9a2b-35693f05887e)

**Comment by mhutch** [comment]
This was fixed in https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/194. I'll publish an update with this fix in the next couple days.
