### ISSUE TITLE
SatelliteResourceLanguages does not support comma delimiters

### ISSUE THREAD

**Issue by martincostello** [mhutch/MonoDevelop.MSBuildEditor#182]
The `SatelliteResourceLanguages` property raises errors if commas are used to delimit the values. For example:

```xml
<SatelliteResourceLanguages>en,en-GB,en-US,qps-Ploc</SatelliteResourceLanguages>
```

MSBuild processes the values and behaves correctly if commas are used, so a warning should not be raised if they are used instead of semi-colons.

**Comment by mhutch** [comment]
This one is documented as semicolons and there is no standardized splitting behavior for properties, as that's up to the tasks that use the properties. I'll update the schema to match actual behavior.
