### ISSUE TITLE
IDE warnings are not recognised

### ISSUE THREAD

**Issue by martincostello** [mhutch/MonoDevelop.MSBuildEditor#184]
When `IDE` warnings are suppressed with `NoWarn`, the error codes are not recognised:

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/1439341/c33fea32-60e2-4e8d-bc42-ed60a8b882da)

`IDE*` warnings should be recognised.

**Comment by slang25** [comment]
Looks like there is an intent to add them: https://github.com/mhutch/MonoDevelop.MSBuildEditor/issues/171#issuecomment-2025527717

**Comment by mhutch** [comment]
Yes #171 added many more codes (`CA*`, `IL*` etc) but the `IDE*` ones are still missing so I'll leave this issue open to track that.

**Comment by peymanr34** [comment]
Please also consider `VSTHRD*` from https://github.com/microsoft/vs-threading/blob/main/doc/analyzers/index.md

**Comment by HakamFostok** [comment]
I was working on this, I will open the PR, and if you have a note for this please let me know and I will modify it
