### ISSUE TITLE
`nullable` is not recognised as valid in WarningsAsErrors

### ISSUE THREAD

**Issue by JakeYallop** [mhutch/MonoDevelop.MSBuildEditor#202]
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/30874283/2f4a29d0-b1f2-46b3-a0b7-015059119233)

Setting `nullable` for `<WarningsAsErrors>` turns on errors for all nullability warnings, however, it is not accepted as a valid value.

**Comment by mhutch** [comment]
This was fixed in https://github.com/mhutch/MonoDevelop.MSBuildEditor/commit/156a9766afa7291348feb513f9b4f54a7c793e19. I'll release an update in the next couple days.
