### ISSUE TITLE
The value is not a valid suffixed version format

### ISSUE THREAD

**Issue by AESSoftware** [mhutch/MonoDevelop.MSBuildEditor#204]
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/54413891/0bffecc0-2ae8-4924-9c32-2d06f4019045)

But it is valid - it's just a 'locked' version i.e. from https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort

```
<!-- Install/restore version 6.1.0, and do not change during update. -->
<package id="ExamplePackage" version="6.1.0" allowedVersions="[6.1.0]" />

```

**Comment by mhutch** [comment]
Yup this was fixed in https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/194. I'll publish an update with this fix in the next couple days.
