### ISSUE TITLE
Native AoT properties are not recognised

### ISSUE THREAD

**Issue by martincostello** [mhutch/MonoDevelop.MSBuildEditor#205]
Properties related to native AoT publishing are not recognised, such as `IlcInstructionSet`, `IlcGenerateDgmlFile`, `IlcGenerateMstatFile` and [`OptimizationPreference`](https://learn.microsoft.com/dotnet/core/deploying/native-aot/optimizing):

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/1439341/6705d09e-8693-4585-8558-9c7eaf32f74c)

**Comment by mhutch** [comment]
Given these are pretty esoteric and don't seems to be documented aside from some internal docs in the runtime repo, I probably won't add them myself any time soon, but contributions are welcome and I'm happy to give pointers!

CoreRT could also ship a `.buildschema.json` with their MSBuild targets, which would be easier to keep up to date  ;)

**Comment by martincostello** [comment]
That's fair - I'd be happy to contribute something as a starting point if you can give me some pointers on where to start.

**Comment by mhutch** [comment]
I added some docs to the wiki https://github.com/mhutch/MonoDevelop.MSBuildEditor/wiki/Contributing-to-built-in-schemas
