### ISSUE TITLE
An error appears when adding an asterisk "*" to install the latest version of packages

### ISSUE THREAD

**Issue by hishamsd** [mhutch/MonoDevelop.MSBuildEditor#211]
An error appears when adding an asterisk "*" to install the latest version of packages
Example :

<PackageReference Include="Microsoft.WindowsAppSDK" Version="*" /> 

![Screenshot 2024-04-20 235536](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/149822637/6dd17fdf-ed52-45e3-b5e5-957fb03be21a)

Error In: 
      "MonoDevelop.MSBuild/Language/MSBuildDocumentValidator.cs"     =>      Line 693

**Comment by mhutch** [comment]
This was fixed in #194. I'll publish an update with this fix in the next couple days.
