### ISSUE TITLE
Completion reappears only after you press backspace all the way back.

### ISSUE THREAD

**Issue by lohitakshgupta** [mhutch/MonoDevelop.MSBuildEditor#22]
When you are deleting the object that was committed earlier, the completion list will not reappear with the remaining prefix of this object left after deletion.

_Details:_
Let's say the following object `netcoreapp2.0 ` is committed:
![image](https://user-images.githubusercontent.com/15707566/63473162-50cfa700-c429-11e9-8b47-a8c6e49da1cc.png)

Now on deleting `2.0` from `netcoreapp2.0 `, the above completion list should have automatically appeared as the `backspace` is being pressed:
![image](https://user-images.githubusercontent.com/15707566/63473312-dce1ce80-c429-11e9-9a61-8cbd7ea24a97.png)

The completion list reappears only after explicitly pressing `ctrl + space`.

**Comment by mhutch** [comment]
This is as intended, completion is only automatically triggered at the start of a token, else it would get really annoying when deleting stuff.
