### ISSUE TITLE
XML autocomplete removes too much

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.MSBuildEditor#220]
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/679326/a2c58314-db0b-4250-8428-25ca37b27b35)

Hit Ctrl+Space and pick the folder from menu:

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/679326/07d0669a-4462-457d-8f3c-ba90c7764ef6)

Press enter. Expected: first image. Actual:

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/679326/ab8c2caf-3b09-43e3-b2fe-7c1f15528afe)

@miloush

**Comment by mhutch** [comment]
Is this with main? I can't find the commit but I feel like I fixed something related to this recently.

**Comment by KirillOsenkov** [comment]
No, we will update to latest and retest

**Comment by KirillOsenkov** [comment]
I can confirm this is now fixed.

However if the caret is not at the end of the word, it completes the remainder of the word (unlike C#):
![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/679326/ecaa8323-a1a8-4723-a02d-7b4f3a43181b)

Not sure if this is the desired behavior.

Maybe if there's a single completion, and the word in the editor around the trigger point matches the completion exactly, the completion shouldn't show but the caret should move to the end of the word? This is how C# works.

**Comment by KirillOsenkov** [comment]
In any event, this perhaps should be opened in a new bug, since the original repro scenario is now fixed.

**Comment by KirillOsenkov** [comment]
Filed #227 and closing this one.
