### ISSUE TITLE
`PrivateAssets` and `IncludeAssets` are showing warnings as unknown

### ISSUE THREAD

**Issue by HakamFostok** [mhutch/MonoDevelop.MSBuildEditor#233]
In the `Directory.Packages.props` file, I have a the following

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/12747172/a320198a-15ec-4364-a5d9-67b97d8d53a5)

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/12747172/984fd29d-879a-49c5-8133-5917445e7887)

In both cases `PackageVersion` and `GlobalPackageReference` the `PrivateAssets` and `IncludeAssets` are showing a yellow underline and the following warning

![image](https://github.com/mhutch/MonoDevelop.MSBuildEditor/assets/12747172/73159132-32ce-4173-bc5d-34d9dff7344f)
--------------------------
Note: I would like to help in solving this if provided with proper guidance, I already contributed to this amazing project and I would love to do that again, if I can

Thank you ver much

**Comment by mhutch** [comment]
Hi! The correct fix would be to add `GlobalPackageReference` to the list of items these metadata apply to: https://github.com/mhutch/MonoDevelop.MSBuildEditor/blob/d95cfbc8e5b6f6a499f8956a6f6a2394db02abfe/MonoDevelop.MSBuild/Schemas/CommonTargets.buildschema.json#L985

**Comment by HakamFostok** [comment]
here is the PR: https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/234

**Comment by mhutch** [comment]
Closing as these metadata are ignored per [the comment in the PR thread](https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/234#issuecomment-2125876458)
