### ISSUE TITLE
Package Reference TreatAsUsed is not recognized

### ISSUE THREAD

**Issue by Thieum** [mhutch/MonoDevelop.MSBuildEditor#242]
This flag is used to prevent dependencies cleaner from Visual Studio to remove the reference.

![image](https://github.com/user-attachments/assets/ac8bab66-4a52-4600-a5ad-175cf645e2de)

**Comment by KirillOsenkov** [comment]
do you have a link where we can read more about this metadata? I haven't seen this beforep

**Comment by msedi** [comment]
The same here:

![image](https://github.com/user-attachments/assets/8f558ca0-8725-4459-a169-5cb13ae96adc)

see here: https://stackoverflow.com/questions/70452355/keep-special-projectreference-when-using-remove-unused-reference

From reddit:
https://www.reddit.com/r/VisualStudio/comments/s29ir2/how_to_keep_projectreference_when_using_remove/

> The microsoft docs also do say nothing about this. Also the project schema definition of the csproj does not say anything.

Does this help?
