### ISSUE TITLE
`Using` Include validation is incorrect for types that have CLR generics

### ISSUE THREAD

**Issue by baronfel** [mhutch/MonoDevelop.MSBuildEditor#253]
Given the following snippet from a C# project file:

```xml
 <!-- Global usings -->
  <!-- See: https://learn.microsoft.com/dotnet/core/project-sdk/msbuild-props#using -->
  <ItemGroup>
    <!-- Aliases -->
    <!-- Note: '%3C' is for '<' and '%3E' is for '>' -->
    <Using Include="System.Collections.Generic.Dictionary%3CMicrosoft.NET.Sdk.WorkloadManifestReader.WorkloadId, Microsoft.NET.Sdk.WorkloadManifestReader.WorkloadDefinition%3E" Alias="WorkloadCollection" />
  </ItemGroup>
```

![image](https://github.com/user-attachments/assets/6c64e951-63dd-4519-9f8d-d9b23d05d809)

The extension errors on the `Include` because of the escaped `<` and `>` characters. It might be useful to
* define a data type that describes a CLR type name and explicitly allows these escaped characters, and
* apply that data type to `Include` on `Using` items

**Comment by mhutch** [comment]
There is are "clr-type", "clr-type-name" and "clr-namespace" types, and it looks like this uses "clr-namespace", whereas it should be "clr-type" - or maybe "csharp-type", as the syntax for generic is not universal.

However, handling of both XML and MSBuild escaping is a bit iffy in general, and I think that's the main problem here.
