### ISSUE TITLE
How to install this extension

### ISSUE THREAD

**Issue by jnm2** [mhutch/MonoDevelop.MSBuildEditor#50]
The readme says:

> The MSBuild Editor extension provides improved support for editing MSBuild files in Visual Studio and Visual Studio for Mac. It can be installed from the Extension Manager.

I tried searching `msbuild editor`, `msbuildeditor`, and `MonoDevelop.MSBuildEditor` in the extension manager, and I'm not finding it in the gallery or at https://marketplace.visualstudio.com/. Is there a download link for the VSIX?

**Comment by japj** [comment]
As far as I can tell, the only place where you can find a prebuild vsix  is from the GitHub actions build pipeline for windows https://github.com/mhutch/MonoDevelop.MSBuildEditor/actions?query=workflow%3A%22Visual+Studio%22 (this build is triggered on commits, so it is not an officially released binary)

**Comment by DmitriyShepelev** [comment]
The latest Windows build is expired as of 3/7/23—would be great if this issue was addressed.
